Watt this in situ carriage block lubrication
VoronDesign/VoronUsers pull request #1015
Opened 2023-12-23 06:11 UTC by jpeterse

### Which mods are added by this PR?
a mod that allow lubrication of the linear rail guide blocks while install in the printer.

### How was it tested?
made the mod to my own 2.4r2 printer

### Any background context you want to provide?
With the speed of the Voron printers print at, the distance traveled quick add up. Which means the manufacturers recommended lubrication intervals, comes up sooner than ever before. This mod allow for lubricating the guide blocks without any disassembly of the printer.

### Screenshots (if appropriate)
Several pictures are included in the submission, including a short video demonstrating the concept.

### ⚠️⚠️**PLEASE READ AND COMPLETE THE CHECKLIST BELOW**⚠️⚠️

  * [X ] I have read the rules available [here](https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules) and
        my mod adheres to these rules.
  * [ X] This mod was created by myself and I agree to publish it under the repository
        [license](https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md)

2023-12-23 15:15 UTC, MapleLeafMakers requested changes
The .webp files here appear to be redundant, as there are already png versions of them all. can the .webp files be removed?

2023-12-23 15:15 UTC, MapleLeafMakers commented on printer_mods/watt-this/in-situ_linear_rail_greasing/.metadata.yml
> +- greasing_concept.step
Files listed in the metadata need to include the path to that file, this should be:
` - CAD/greasing_concept.step`

2023-12-23 15:15 UTC, MapleLeafMakers commented on printer_mods/watt-this/in-situ_linear_rail_greasing/.metadata.yml
> +images:
All the files listed here should be prefixed with `IMG/`

2023-12-25 13:25 UTC, FHeilmann commented
@jpeterse I see you have added a video to your PR, this video is rather large. Would it be possible to reduce that video size a bit? The reason for my request is that VoronUsers is already ~10GB for a single checkout and we'd like to try and keep the overall size as small as possible. As an alternative, you can host the video unlisted on youtube and add a link to your readme to that instead.

2023-12-26 02:02 UTC, jpeterse commented
Moved the video as requested

2023-12-27 16:59 UTC, merged