Flush mount for hdmi and usb c (#1)
VoronDesign/VoronUsers pull request #1031
Opened 2024-01-21 21:23 UTC by ppak10

### Which mods are added by this PR?

Cable Port Flush Mount Skirt

### How was it tested?

This mod was printed and fitted on the 250, 300, and 350 rear skirt variants of the Voron 2.4

The mod is currently in use on a 350 variant of the Voron 2.4

![350_Installed](https://github.com/VoronDesign/VoronUsers/assets/37542469/19c21434-85f6-4b88-8645-df4f3f21f1f4)

### Any background context you want to provide?

With the Raspberry Pi mounted on the underside of the printer, it makes it difficult to access some of the debug ports of the device. Thus, this mod provides an easy port access to many of the essential ports of the computer.

### Screenshots (if appropriate)

![250_300_350_Render](https://github.com/VoronDesign/VoronUsers/assets/37542469/d2adb8c0-192d-41d7-ad75-286995b3880c)

### ⚠️⚠️**PLEASE READ AND COMPLETE THE CHECKLIST BELOW**⚠️⚠️

  * [x] I have read the rules available [here](https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules) and
        my mod adheres to these rules.
  * [x] This mod was created by myself and I agree to publish it under the repository
        [license](https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md)

2024-01-21 21:47 UTC, MediumRare-david commented on printer_mods/ppak10/Cable_Port_Flush_Mount_Skirt/README.md
> +
up to you, but you _may_ want to add that it is a friction fit with no additional hardware required besides the BATIGE port.

2024-01-21 21:49 UTC, MediumRare-david reviewed
overall really cool mod. Very simple and could be very useful!

2024-01-21 22:19 UTC, MediumRare-david commented on printer_mods/ppak10/Cable_Port_Flush_Mount_Skirt/STL/rear_center_skirt_350.STL
would you be able to add some 0.4mm chamfer to each of the holes  on the side touching the build plate in the skirts to compensate for printing tolerances?

2024-01-21 22:26 UTC, MediumRare-david commented on printer_mods/ppak10/Cable_Port_Flush_Mount_Skirt/STL/rear_center_skirt_350.STL
Regarding the file sizes... Each of the STLs are quite large. Is there a way that you could export them in such a way to reduce them to less than 3mb? When I open your CAD files and export to STL I am able to get you're largest object to 2.8mb at a high resolution. If you need me (or another reviewer) to export it for you, woe can do that :-)

2024-01-22 17:22 UTC, MediumRare-david commented on printer_mods/ppak10/Cable_Port_Flush_Mount_Skirt/Images/batige_mount.jpg
Hey thanks for all the changes you made! The only thing  I can see that may be a issue is the use of this picture in regards to copyright. It would be preferred if **you** took a picture of the BATIGE plug physically just to be safe :-)

2024-01-23 00:43 UTC, ppak10 commented
Thanks for reviewing this PR and my first Voron Mod!

2024-01-23 02:34 UTC, MediumRare-david approved these changes
Very nice. Thanks for being willing to change those things!

2024-01-23 03:38 UTC, MapleLeafMakers requested changes

2024-01-23 03:38 UTC, MapleLeafMakers commented on printer_mods/ppak10/Cable_Port_Flush_Mount_Skirt/README.md
> +  <img src="./Images/250.jpeg" alt="250" width="250"/>
this image, and all of the other .jpeg's here appear as broken image links, due to the links containing `.jpeg` while the files are actually named `.JPEG`
![image](https://github.com/VoronDesign/VoronUsers/assets/105010153/aa59875b-e769-4158-8487-3827fa98084d)

2024-01-23 03:38 UTC, MapleLeafMakers commented on printer_mods/ppak10/Cable_Port_Flush_Mount_Skirt/README.md
> +<div style="justify-content: center; display: flex;">
this doesn't actually work, github ignores it, you can see here the image is still left-aligned:
![image](https://github.com/VoronDesign/VoronUsers/assets/105010153/8e48b62b-b57f-4396-8dd0-33cfabc2eba5)

We actually discourage any HTML in the README file, though we've made an exception for images to allow for sizing, 
I think these should just be removed though.

2024-01-23 03:58 UTC, MapleLeafMakers commented
One other minor thing, there are 2 very similar images included `All_Sizes.JPEG` and `All_Sizes_2.JPEG`, and neither one is referenced from the README.md.  It's ok to include extra images but one of those 2 is probably unnecessary `All_Sizes_2.JPEG` is a better one IMO :)

2024-01-23 04:03 UTC, MapleLeafMakers commented on printer_mods/ppak10/Cable_Port_Flush_Mount_Skirt/README.md
> +![250_300_350_Render](./Images/250_300_350_render.png)
Much nicer, this one is still broken though: the `R` in `render` should be capitalized.

2024-01-23 04:08 UTC, MapleLeafMakers approved these changes

2024-01-23 04:08 UTC, ppak10 commented
Thanks! @MapleLeafMakers @MediumRare-david

2024-01-25 17:26 UTC, merged