feat: add switchwire cyd screen case files
VoronDesign/VoronUsers pull request #1041
Opened 2024-03-25 11:35 UTC by Reemuson

### Which mods are added by this PR?
- SW_CYD_SCREEN_CASE

### How was it tested?
Tested on my Aquilawire SW.807

### Any background context you want to provide?
Posted on [Printables](https://www.printables.com/model/814999-voron-switchwire-cyd-screen-case)

### ⚠️⚠️**PLEASE READ AND COMPLETE THE CHECKLIST BELOW**⚠️⚠️

  * [x] I have read the rules available [here](https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules) and
        my mod adheres to these rules.
  * [x] This mod was created by myself and I agree to publish it under the repository
        [license](https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md)

2024-03-25 21:46 UTC, chirpy2605 requested changes

2024-03-25 21:46 UTC, chirpy2605 commented on printer_mods/Reemuson/SW_CYD_Screen_Case/STL/switchwire_cyd_case_front.stl
Can you please orientate this part so it is the correct way up for printing as it's currently the wrong way up

2024-03-25 21:46 UTC, chirpy2605 commented on printer_mods/Reemuson/SW_CYD_Screen_Case/README.md
I think it would help if you could link to at least one of your images in this README file. This will show users what it will look like and the animated GIF will give them instruction on how it fits together. Please use relative links to at least one image

2024-03-26 02:50 UTC, Reemuson commented on printer_mods/Reemuson/SW_CYD_Screen_Case/STL/switchwire_cyd_case_front.stl
I can definitely do that.

2024-03-26 02:51 UTC, Reemuson commented on printer_mods/Reemuson/SW_CYD_Screen_Case/README.md
Ok that's doable, I was under the impression that linking the images in the yaml was sufficient. I'm not quite familiar with the implementation the website is using to pull images from the users mod

2024-03-26 08:29 UTC, chirpy2605 approved these changes

2024-03-26 08:32 UTC, chirpy2605 commented
Look good to me

2024-03-26 12:32 UTC, jontek2 approved these changes
LGTM!

For future updates or other mods you can look into adding counterbore bridging to some of the countersunk holes in your models. Make it clean and easier to print+

2024-03-26 16:09 UTC, chirpy2605 approved these changes

2024-03-27 00:45 UTC, Reemuson commented
> LGTM!
> 
> 
> 
> For future updates or other mods you can look into adding counterbore bridging to some of the countersunk holes in your models. Make it clean and easier to print+

Definitely an oversight on my side. Didn't cross my mind but am quite familiar with the process. Haven't designed something for FDM in a while so it wasn't on the brain. I'll get that sorted if you can wait before merge.

2024-03-27 14:31 UTC, jontek2 commented
> > LGTM!
> > For future updates or other mods you can look into adding counterbore bridging to some of the countersunk holes in your models. Make it clean and easier to print+
> 
> Definitely an oversight on my side. Didn't cross my mind but am quite familiar with the process. Haven't designed something for FDM in a while so it wasn't on the brain. I'll get that sorted if you can wait before merge.

Awesome! Thanks.

2024-03-27 15:13 UTC, chirpy2605 approved these changes

2024-03-31 00:45 UTC, merged