Ballpoint pen spring DIN clips assortment
VoronDesign/VoronUsers pull request #1048
Opened 2024-06-04 11:54 UTC by aeresov

### Which mods are added by this PR?
An assortment of spring-loaded DIN clips for electronics bay, designed as drop-in replacement for original V2.4/VT rail clips, including PSU mounts.  Common ballpoint pen springs are used.

### How was it tested?
I tested it on my V2.4r2. It should be compatible with Trident as it uses the same DIN rails.

### Any background context you want to provide?
Nothing in particular.

### Screenshots (if appropriate)
There are detailed photos in step-by-step instruction I put in readme.

### ⚠️⚠️**PLEASE READ AND COMPLETE THE CHECKLIST BELOW**⚠️⚠️

  * [x] I have read the rules available [here](https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules) and
        my mod adheres to these rules.
  * [x] This mod was created by myself and I agree to publish it under the repository
        [license](https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md)

2024-06-17 15:26 UTC, chirpy2605 requested changes

2024-06-17 15:26 UTC, chirpy2605 commented on printer_mods/aeresov/ballpoint-pen-spring-DIN-clips/.metadata.yml
You have 3 of the image files in the meta file as .png whereas they are actually .png files, so need correcting here

2024-06-17 23:40 UTC, aeresov commented on printer_mods/aeresov/ballpoint-pen-spring-DIN-clips/.metadata.yml
Ah. Sorry, overlooked.

2024-06-19 10:03 UTC, chirpy2605 approved these changes

2024-06-19 10:03 UTC, chirpy2605 commented
Me too!

2024-06-19 10:47 UTC, merged