Double_GEAR_ratio_Z
VoronDesign/VoronUsers pull request #1052
Opened 2024-07-12 19:55 UTC by zzp8202

### Which mods are added by this PR?
One 

### How was it tested?
Test by myself.

### Any background context you want to provide?
Enabling the Voron 2.4 Gantry to Defy Gravity
### Screenshots (if appropriate)

### ⚠️⚠️**PLEASE READ AND COMPLETE THE CHECKLIST BELOW**⚠️⚠️

  * [ ] I have read the rules available [here](https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules) and
        my mod adheres to these rules.
  * [ ] This mod was created by myself and I agree to publish it under the repository
        [license](https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md)

2024-07-12 23:03 UTC, chirpy2605 commented on printer_mods/ZZP8202/Double_GEAR_ratio_Z/Images/Photo.jpg
Could you resize this pic as it's over 2MB in size. For example, I've attached a resized one that is 10% of the file size
![Photo](https://github.com/user-attachments/assets/cf08401d-0e96-4dac-a239-36202d670bbe)

2024-07-12 23:07 UTC, chirpy2605 commented on printer_mods/ZZP8202/Double_GEAR_ratio_Z/README.md
Could you please add a section that explains exactly how to assemble this Modification on the printer using text and pictures/images to details how it goes together.

2024-07-13 18:04 UTC, zzp8202 commented
I have resize the photo , and  add assemble instructions with gif image.

2024-07-13 19:05 UTC, zzp8202 commented
I have resize the photo ,  add assemble instructions with gif image, and edit the '.metadata.yml' file.

2024-07-14 09:38 UTC, chirpy2605 requested changes

2024-07-14 09:38 UTC, chirpy2605 commented on printer_mods/ZZP8202/Double_GEAR_ratio_Z/README.md
> +![Photo](Images/ezgif.com-resize.gif)
The README.md is referencing "Images/ezgif.com-resize.gif" but that file doesn't exist

2024-07-14 09:38 UTC, chirpy2605 commented on printer_mods/ZZP8202/Double_GEAR_ratio_Z/.metadata.yml
> +-Other/Assemble_Instructions/Pulley_Holder.gif
There are some formatting errors in the YAML file. "The Other:" section should be first and then the subsequent entries need a space after the "-" in "-/Other/..."

Like so:
```
Other:
- Other/Assemble_Instructions/Pulley_Holder.gif
- Other/Assemble_Instructions/Z_Bearing_Block_Bottom_With_Pulley.gif
- Other/Assemble_Instructions/BOM/Pulley_Holder_X4_BOM.png
- Other/Assemble_Instructions/BOM/Z_Bearing_Block_Bottom_With_Pulley_BOM.png
- Other/Assemble_Instructions/BOM/Pulley_Holder_X4_BOM.pdf
- Other/Assemble_Instructions/BOM/Z_Bearing_Block_Bottom_With_Pulley_BOM.pdf

```

2024-07-14 10:13 UTC, zzp8202 commented
sorry for mistake, I have fix it as your marked.

2024-07-14 10:55 UTC, chirpy2605 approved these changes
All looks good to me

2024-07-14 11:21 UTC, jontek2 commented
Hey @zzp8202,

Thanks for submitting, very cool mod!

Upon my review I've noticed that:

1. "/STL/Z_Bearing_Block_Bottom_With_Pulley_Left_A_x2.STL" has the Voron-logo upside down.

2. The description in the README.md is "Double_GEAR_ratio_Z_belt_assembly_with_spherical_bearing_connection". Maybe you could write a short sentence about how it can help with gantry sagging?

Other than that it looks good to me and once the two issues mentioned above has been dealt with i'll happily approve this mod.

Thanks!

2024-07-14 14:44 UTC, jontek2 approved these changes
LGTM!

2024-07-14 14:53 UTC, merged