Added V0 Pi 0 Mount
VoronDesign/VoronUsers pull request #176
Opened 2020-10-21 19:14 UTC by johnderuntz

Created KenadyDwag44 Folder and added V0 Pi 0 mounting bracket.

Tested by myself and uses no new hardware.

  * [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

#### How was it tested? 

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2020-11-06 20:50 UTC, KiloQubit requested changes
Thanks for your mod.  Can you update `printer_mods/README.md` to add your mod to the table there in alphabetical order?  Also, if you have any pictures of the mod, feel free to include them.

Checked:
- mod in correct directory
- no spaces in directory or file names
- there's a readme for the mod
- STL is oriented correctly and doesn't require supports

2020-11-09 01:44 UTC, johnderuntz commented
Updated the README to add my information!

2020-11-09 01:46 UTC, KiloQubit approved these changes
Looks good, thanks.

2020-11-13 20:24 UTC, KiloQubit requested changes
Please fix the orientation on the SW_lightbar* STLs, they're not in a printable orientation.

2020-11-13 20:24 UTC, KiloQubit commented on printer_mods/KenadyDwag44/sw_lightbar/README.md
> +## Voron V0 Raspberry Pi 0 Mount
This readme talks about a Pi Zero bracket, but the mod is for an LED holder, please update this README to describe the LED holder mod.

2020-11-13 20:37 UTC, johnderuntz commented
Sorry, accidentally pushed the wrong file into the wrong pull request. Closing pull request because pull request #190 is the actual request

2020-11-13 20:38 UTC, johnderuntz commented
Reopening

2020-11-13 20:42 UTC, KiloQubit approved these changes
Cleaned up PR looks good.

2020-12-06 23:20 UTC, raymondh2 approved these changes

2020-12-09 18:40 UTC, FHeilmann requested changes
This mod is kind of doing the same thing as [this mod](https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/Nomsplease/V0_Mods/pi_zero_camera_mount). Are there any significant advantages of this mod?

2020-12-13 07:32 UTC, johnderuntz commented
> This mod is kind of doing the same thing as [this mod](https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/Nomsplease/V0_Mods/pi_zero_camera_mount). Are there any significant advantages of this mod?

Sorry, I didn't realize that mount existed before i submitted mine.

The main advantage of my mount compared to the other is that it is smaller and uses half the filament the other mod uses, but serves the purpose just as good. It was made smaller in order to fit a usb expansion board on the pi 0.

Thanks!

2021-05-02 23:56 UTC, KiloQubit commented
Closing as a duplicate mod.

2021-05-02 23:56 UTC, closed without merging