Volcano Part Cooling Shroud for AB
VoronDesign/VoronUsers pull request #222
Opened 2021-01-04 10:00 UTC by perikanttila

* [x ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Original E3D V6 part cooling shroud was the source
#### How was it tested? 
Printed it our
#### Any background context you want to provide?
no
#### Screenshots (if appropriate)
no
#### Further notes
no

2021-03-07 20:27 UTC, KiloQubit requested changes
Thanks for your PR.  There are just two small changes needed.

Please remove the space from the STL filename, e.g. rename it to `Volcano_Shroud.stl`

2021-03-07 20:27 UTC, KiloQubit commented on printer_mods/README.md
> +|karip|[Volcano Shroud](./karip/volcano_shroud)|Vocano Shroud|:x:|:x:|:heavy_check_mark:|:grey_question:|
Please move this line up so that it's in alphanumeric order by username.

2021-04-12 15:53 UTC, KiloQubit commented
Do you intend to update this PR to address the review comments?

2021-04-13 08:27 UTC, perikanttila commented
I will, it has been a bit busy lately


> On 12. Apr 2021, at 18.53, KiloQubit ***@***.***> wrote:
> 
> ﻿
> Do you intend to update this PR to address the review comments?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-27 18:59 UTC, KiloQubit commented
Hi, are you still planning to update this mod?

2021-06-28 05:07 UTC, perikanttila commented
Sorry yes, i was moving and not able to update will do it soon
Thanks


> On 27. Jun 2021, at 21.59, KiloQubit ***@***.***> wrote:
> 
> ﻿
> Hi, are you still planning to update this mod?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-30 19:01 UTC, bryanboettcher commented
@perikanttila I'm willing to take over the remaining housekeeping on this PR if you'd be OK with that.

2021-07-31 08:01 UTC, perikanttila commented
Thank you.


> On 30. Jul 2021, at 22.01, Bryan Boettcher ***@***.***> wrote:
> 
> ﻿
> @perikanttila I'm willing to take over the remaining housekeeping on this PR if you'd be OK with that.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-12-03 04:25 UTC, bdbell commented
This still requires the one review item be addressed.  Will it be addressed?

2022-06-25 16:29 UTC, Rhastlyn commented
This is one is quite old, anyone intend to complete this PR?

2022-06-25 16:51 UTC, perikanttila commented
i hope someone does complete it. i can not do it. no skills to complete it

...
Kari

> On 25. Jun 2022, at 19.30, Rhastlyn ***@***.***> wrote:
> 
> ﻿
> This is one is quite old, anyone intend to complete this PR?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-07-17 20:45 UTC, cbc02009 commented
waiting on SB release to revisit finalizing this mod.

2022-08-29 22:51 UTC, cbc02009 commented
Closing due to inactivity.

2022-08-29 22:51 UTC, closed without merging