AB mount for standard dial indicator
VoronDesign/VoronUsers pull request #264
Opened 2021-03-16 02:27 UTC by teookie

* [x ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x ] Submitted STL files are oriented and scaled properly for printing.
  * [x ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Mount for attaching standard dial indicator (not a test indicator) to AB.

#### How was it tested? 
Designed and tested by me. Used to level x rails and create manual bed mesh.

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2021-03-24 23:46 UTC, KiloQubit reviewed
Thanks for your mod!

There's already a dial indicator mount here https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/arkeet/dti-mount , and we try to avoid duplicate mods.  Is there some advantage to your mod over the existing one?

2021-03-25 01:38 UTC, teookie commented
Fits a different style of dial indicator. Existing design is for test
indicators. This one is for standard dial indicator.

-Trent

On Wed, Mar 24, 2021, 6:46 PM KiloQubit ***@***.***> wrote:

> *@KiloQubit* commented on this pull request.
>
> Thanks for your mod!
>
> There's already a dial indicator mount here
> https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/arkeet/dti-mount
> , and we try to avoid duplicate mods. Is there some advantage to your mod
> over the existing one?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/VoronDesign/VoronUsers/pull/264#pullrequestreview-620317967>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADK3YPHTQXJ6SSABAKAL52TTFJ2WJANCNFSM4ZHUW45A>
> .
>

2021-03-25 18:04 UTC, jurisv commented
Yes, totally different beast. Bring it on! :)

2021-03-25 23:41 UTC, KiloQubit requested changes
Thanks for your reply.  Everything looks good except one type in the README noted below.

2021-03-25 23:41 UTC, KiloQubit commented on printer_mods/teookie/AB_dial_indicator_mount/readme.md
> +Usefull for:
Please change `Usefull` to `Useful`

2021-03-26 00:53 UTC, teookie commented on printer_mods/teookie/AB_dial_indicator_mount/readme.md
> +Usefull for:
Typo fixed. Thanks.

2021-03-26 00:57 UTC, KiloQubit approved these changes
Thanks!

2021-03-26 00:57 UTC, merged