V2 endstop relocation
VoronDesign/VoronUsers pull request #278
Opened 2021-04-09 17:39 UTC by hartk1213

* [X] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [X] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [X] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [X] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [X] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [X] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [X] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [X] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [X] Submitted STL files are oriented and scaled properly for printing.
  * [X] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
   Y endstop relocation for v2
#### How was it tested? 
 This has been tested by me and a few others on the discord for the past few months 
#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2021-04-11 23:32 UTC, KiloQubit requested changes
Thanks for your mod!

I'm a bit confused - this is the endstop relocation mod, why are you adding step files to the pins mod?  And it looks like they're the same step files in the pins mod and this mod.

2021-04-12 21:46 UTC, hartk1213 commented
> Thanks for your mod!
> 
> I'm a bit confused - this is the endstop relocation mod, why are you adding step files to the pins mod? And it looks like they're the same step files in the pins mod and this mod.

the reason i added them to this pins mod is because i made a version that is for the stock A drive as well as the Pinned A drive and the step files look similar but one is for pins and one is for stock 2.4 non pinned a drive , the holes are slightly different dimensions

2021-04-22 17:14 UTC, hartk1213 commented
@KiloQubit i have updated this pr title to better indicate what is being added, i have added the MGN12 pinned XY joints to the Pinned mod folders, moved the endstop relocation files to the correct folder, and added links to all the mods that work together. 

let me know if there is anything that needs to be changed 

Thanks 
-hart

2021-04-25 17:59 UTC, KiloQubit requested changes
Thanks for your mod!  Comments below.

2021-04-25 17:59 UTC, KiloQubit commented on printer_mods/hartk1213/Voron2.4_Pins_Mod/README.md
> +*NOTE: There are now 2 versions of these files , 1 set for Stock 2.4 and 1 set for  [Arkeets MGN12](https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/arkeet/mgn12)*
Can you make this a relative link?

    [Arkeet's MGN12 mod](../../arkeet/mgn12)

2021-04-25 17:59 UTC, KiloQubit commented on printer_mods/hartk1213/Voron2.4_Pins_Mod/README.md
> +There is a new file for the A Drive to go along with [Arkeets MGN12](https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/arkeet/mgn12) mod that has the X endstop on the toolhead
Change to relative link

    ... to go along with [Arkeet's MGN12 mod](../../arkeet/mgn12) that has the X endstop ...

2021-04-25 17:59 UTC, KiloQubit commented on printer_mods/hartk1213/Voron2.4_Pins_Mod/README.md
> +the files for the endstop relocation mod are here [Voron2.4_Y_Endstop_Relocation](https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/hartk1213/Voron2.4_Y_Endstop_Relocation)
Change to relative link

    [Voron2.4_Y_Endstop_Relocation](../Voron2.4_Y_Endstop_Relocation)

2021-04-25 17:59 UTC, KiloQubit commented on printer_mods/hartk1213/Voron2.4_Pins_Mod/README.md
`MGN12_xy_join_left_upper_pinnned.STL` is upside down

2021-04-25 17:59 UTC, KiloQubit commented on printer_mods/hartk1213/Voron2.4_Y_Endstop_Relocation/README.md
> +This mod is for the V2 A Drive to go along with [Arkeets MGN12](https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/arkeet/mgn12) mod that has the X endstop on the toolhead and that is
Change to relative link and fix the run-on sentence.  Here's the whole paragraph rewritten:

    This mod moves the Y endstop to the A drive, to go along with [Arkeet's MGN12 mod](../../arkeet/mgn12)
    that has the X endstop on the toolhead.  This mod requires a 2 pin JST-XH to be soldered to the
    switch.  The best way I have done it is to solder the wires to the JST-XH first, install it with a dab
    of super glue, then solder the wires to the Omron switch.

2021-04-25 17:59 UTC, KiloQubit commented on printer_mods/hartk1213/Voron2.4_Y_Endstop_Relocation/README.md
> +There are 2 different files non pinned version
add a `-`

    There are 2 different files - non pinned version:

2021-04-25 17:59 UTC, KiloQubit commented on printer_mods/hartk1213/Voron2.4_Y_Endstop_Relocation/README.md
> +pinned verion since this mod also works with as well with the Pin mod here [Voron2.4_Pins_Mod](https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/hartk1213/Voron2.4_Pins_Mod)
misspelled version, parens, relative link

    pinned version (since this mod also works with the [Voron2.4_Pins_Mod](../Voron2.4_Pins_Mod)):

2021-04-26 21:42 UTC, KiloQubit approved these changes
Thanks for the updates!

2021-04-26 21:42 UTC, merged