New LED mount and exhaust filter housing
VoronDesign/VoronUsers pull request #284
Opened 2021-04-11 15:23 UTC by 42bios

* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
a new LED mount and a new exhaust filter housing
#### How was it tested? 
printed and used on my voron
#### Any background context you want to provide?

#### Screenshots (if appropriate)
in folders
#### Further notes

2021-04-13 12:18 UTC, 42bios commented
Added corner panel clip with cable path

2021-05-01 16:10 UTC, KiloQubit requested changes
Thanks for your mod!  Please see requested changes below.

- `exhaust_filter_housing_side/exhaust_filter_housing_side.textClipping` - remove this file, and add the missing STL for the exhaust housing
- `LED_mount/AngryLED_{l,r}_v1.stl` - add a chamfer under the unsupported overhang in both files
<img width="364" alt="Screen Shot 2021-05-01 at 11 55 34" src="https://user-images.githubusercontent.com/69389593/116787799-4b3ab900-aa74-11eb-9947-dc280278fb21.png">

2021-05-01 16:10 UTC, KiloQubit commented on printer_mods/42bios/corner_panel_clip_cable/README.md
> +Corner panel clip with a internal cable path, so you can route the cables around the panel and corner.<br>
Replace `a internal` with `an internal`.

2021-05-01 16:10 UTC, KiloQubit commented on printer_mods/42bios/corner_panel_clip_cable/README.md
> +corner_panel_clip_top_4mm.stl is 4mm and corner_panel_clip_bottom_3_5mm.stl is 3.5mm hight, <br>
Replace `hight` with `height`.

2021-05-02 14:44 UTC, 42bios commented
@KiloQubit thanks for the hint! everything should be right now

2021-05-02 15:37 UTC, KiloQubit commented
`LED_mount/AngryLED_r_v1.stl` looks completely broken now
<img width="336" alt="Screen Shot 2021-05-02 at 11 31 11" src="https://user-images.githubusercontent.com/69389593/116818544-ec3f7780-ab39-11eb-8148-2abf29b0a572.png">

Same broken problem with `LED_mount/AngryLED_small_2_v1.stl`.

Also, the large AngryLED STLs are marked l/r (left/right I assume), but the small ones are 1/2 - maybe both should use the same convention.

2021-05-06 18:09 UTC, 42bios commented
updated and renamed it :)

2021-05-07 12:21 UTC, KiloQubit commented
Thanks!  One more thing I missed earlier - the fillets on the bottom of all the AngryLED STLs result in an overhang steeper than 45 degrees.  Can you replace them with chamfers, or a combination of chamfer/fillet like on your panel clips?

<img width="495" alt="Screen Shot 2021-05-07 at 08 18 46" src="https://user-images.githubusercontent.com/69389593/117448768-2380a080-af0d-11eb-9bf8-d6be24f23728.png">

2021-05-07 14:52 UTC, 42bios commented
I give my best and try it :D

2021-05-09 16:47 UTC, KiloQubit approved these changes
Thanks for the updates!

2021-05-09 16:47 UTC, merged