Added my sub-folder and two files to help people shim their MGN7H bearing cartridges.
VoronDesign/VoronUsers pull request #297
Opened 2021-04-25 04:51 UTC by lococnc

* [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

#### How was it tested? 

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2021-04-26 01:19 UTC, KiloQubit requested changes
Thanks for your mod!

- Please create another subdirectory for your mod inside `LoCoCNC`, in case you ever have other mods.  So move this mod into `printer_mods/LoCoCNC/MGN7H_Shims/` for example
- Your STL files are not in a printable orientation, please rotate them.
- Fix the oder of mods in the README as noted  below.

2021-04-26 01:19 UTC, KiloQubit commented on printer_mods/README.md
> +|LoCoCNC| [MGN7H Shims](./LoCoCNC/) | Shims for making bearing cartridges coplanar |:heavy_check_mark:|:x:|:x:|:x:|
Please move this down the list so it's in alphabetical order, looks like your line should be after `littleferris`.

2021-04-26 23:29 UTC, lococnc commented
Updated as requested.

2021-04-27 00:53 UTC, KiloQubit requested changes
Thanks for the updates!  Please see one more change below.

2021-04-27 00:53 UTC, KiloQubit commented on printer_mods/README.md
> +|LoCoCNC| [MGN7H Shims](./LoCoCNC/) | Shims for making bearing cartridges coplanar |:heavy_check_mark:|:x:|:x:|:x:|
Update this link to point to your mod in the new directory

    [MGN7H Shims](./LoCoCNC/MGN7H_Shims)

2021-04-27 21:46 UTC, KiloQubit approved these changes
Thanks for the updates!

2021-04-27 21:46 UTC, merged