Add DIN Rail Mount for FYSETC Spider
VoronDesign/VoronUsers pull request #313
Opened 2021-05-12 10:03 UTC by hoschi73

* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

DIN Rail Mount for FYSETC Spider based on the Voron2 Din-Rail-Bracket
 
#### How was it tested? 

All Parts were printed and testfitted (both versions). 

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2021-05-12 14:15 UTC, KiloQubit requested changes
Thanks for your mod!  Please check some changes below.

- Please delete `IMG/horizontal_rail.jpg` and `IMG/vertical.rail.jpg`, since they're already in `IMG/main.jpg`
- You have two copies of `vertical.rail.jpg` - one in `printer_mods/hoschi/FYSETC_Spider_DIN_Mount/IMG/vertical.rail.jpg` and one in `/vertical.rail.jpg` - please remove `/vertical.rail.jpg` as well (the one at the top level)
- Please remove `printer_mods/hoschi/FYSETC_Spider_DIN_Mount/IMG/.del`

2021-05-12 14:15 UTC, KiloQubit commented on printer_mods/hoschi/FYSETC_Spider_DIN_Mount/README.md
> +spider_bracket_horizontal_terminal.stl
Please add `<br/>` after these lines so they don't appear on a single line.  Alternatively use the list syntax https://www.markdownguide.org/basic-syntax/#unordered-lists

2021-05-12 14:15 UTC, KiloQubit commented on printer_mods/hoschi/FYSETC_Spider_DIN_Mount/README.md
> +for vertical mountin:
Replace `mountin` with `mounting`.  Either add `<br/>` at the end of these lines or use the list syntax as above.

2021-05-12 14:15 UTC, KiloQubit commented on printer_mods/hoschi/FYSETC_Spider_DIN_Mount/README.md
> +Required material:
Replace `material` with `materials`.

2021-05-12 23:46 UTC, KiloQubit requested changes
Thanks for the updates.  There are few more things to fix.  The links you tried to add to the README are actually image references, and they're broken.

The jpg file in `/` still hasn't been deleted:
<img width="602" alt="Screen Shot 2021-05-12 at 19 39 12" src="https://user-images.githubusercontent.com/69389593/118057763-9c8f5600-b35a-11eb-961f-09cf72f109b2.png">

2021-05-12 23:46 UTC, KiloQubit commented on printer_mods/hoschi/FYSETC_Spider_DIN_Mount/README.md
> +- 1x printed bracket terminal side of the Spider Board: ![spider_bracket_horizontal_terminal.stl](./STL/spider_bracket_horizontal_terminal.stl)
For simple links, don't put `!` in front of it - this makes it think it's an image, it's not, so it's broken.  Just

    [spider_bracket_horizontal_terminal.stl](./STL/spider_bracket_horizontal_terminal.stl)

should work.

<img width="748" alt="Screen Shot 2021-05-12 at 19 43 19" src="https://user-images.githubusercontent.com/69389593/118057595-5803ba80-b35a-11eb-963c-0768ac846a98.png">

2021-05-13 00:37 UTC, hoschi73 commented
i hope i got it this time. thanks you for your input and patience.

2021-05-13 12:17 UTC, KiloQubit approved these changes
Thanks for the updates!

2021-05-13 12:17 UTC, merged

2021-05-21 08:37 UTC, hoschi73 commented
Hi,
i have a minor update to the mod. (With the original spacers the pins from the power terminals were digging into the mount. Spacer height extended by 1.5 mm).

How can i submit the changes?

Regards 
Sascha