Added a strain relief that mounts a 10 pin micro fit connector on the hotend.
VoronDesign/VoronUsers pull request #332
Opened 2021-05-31 05:03 UTC by lococnc

* [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

#### How was it tested? 

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2021-06-01 23:58 UTC, KiloQubit requested changes
Thanks for your mod!

The part is not printable without supports.  All Voron parts and mods must be printable without supports, so please redesign this to make it more printable.  The bottoms of these print in mid-air:

<img width="439" alt="Screen Shot 2021-06-01 at 19 55 52" src="https://user-images.githubusercontent.com/69389593/120404055-80585680-c313-11eb-81d6-ebd1bf83e322.png">

This overhang is steeper than 45 degrees, please ensure overhangs are no steeper than 45 degrees:

<img width="277" alt="Screen Shot 2021-06-01 at 19 54 09" src="https://user-images.githubusercontent.com/69389593/120403929-3cfde800-c313-11eb-992c-83bbcdcccba9.png">

2021-06-01 23:58 UTC, KiloQubit commented on printer_mods/LoCoCNC/Strain_Relief_w_Microfit/Images/readme.md
> +Images
Please delete this almost-empty file.

2021-06-02 00:02 UTC, lococnc commented
What about putting a support in that the user is meant to cut away with
flush cutters? Kind of like the cable route on the 0.0?

On Tue, Jun 1, 2021 at 6:58 PM KiloQubit ***@***.***> wrote:

> *@KiloQubit* requested changes on this pull request.
>
> Thanks for your mod!
>
> The part is not printable without supports. All Voron parts and mods must
> be printable without supports, so please redesign this to make it more
> printable. The bottoms of these print in mid-air:
>
> [image: Screen Shot 2021-06-01 at 19 55 52]
> <https://user-images.githubusercontent.com/69389593/120404055-80585680-c313-11eb-81d6-ebd1bf83e322.png>
>
> This overhang is steeper than 45 degrees, please ensure overhangs are no
> steeper than 45 degrees:
>
> [image: Screen Shot 2021-06-01 at 19 54 09]
> <https://user-images.githubusercontent.com/69389593/120403929-3cfde800-c313-11eb-992c-83bbcdcccba9.png>
> ------------------------------
>
> In printer_mods/LoCoCNC/Strain_Relief_w_Microfit/Images/readme.md
> <https://github.com/VoronDesign/VoronUsers/pull/332#discussion_r643557978>
> :
>
> > @@ -0,0 +1 @@
> +Images
>
> Please delete this almost-empty file.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/VoronDesign/VoronUsers/pull/332#pullrequestreview-673676779>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALBBLFCCYXHYGP2T54HEJP3TQVXZXANCNFSM452EGD5A>
> .
>

2021-06-02 00:09 UTC, KiloQubit commented
> What about putting a support in that the user is meant to cut away with flush cutters? Kind of like the cable route on the 0.0?
> […](#)

A built-in support is possible if there's no other option.  So you can either modify the mod to not require supports (maybe it can be two parts or have a different geometry), or you can have a built-in support.  If you have a built-in support, make sure that the README tells the user to remove the supports after printing.  The preference is to not require supports at all though, unless absolutely necessary - just like stock Voron parts.

2021-06-03 23:18 UTC, lococnc commented on printer_mods/LoCoCNC/Strain_Relief_w_Microfit/Images/readme.md
> +Images
Done

2021-06-03 23:19 UTC, lococnc commented
Updated to not require supports. Added pic to show area to cut-away with flush cutters after prinitng.

2021-06-05 00:57 UTC, KiloQubit requested changes
Thanks for the update!  Unfortunately some parts of this STL are still not printable as is (circled):

<img width="894" alt="Screen Shot 2021-06-04 at 20 53 49" src="https://user-images.githubusercontent.com/69389593/120874968-32dc2380-c577-11eb-86b6-b313793b264b.png">

2021-06-13 00:55 UTC, lococnc commented
Updated and test printed with no supports on V0.1

2021-06-13 23:28 UTC, KiloQubit approved these changes
Thanks for the update!

2021-06-13 23:28 UTC, merged