Added Articulating Raspberry Pi 7" Display Mount
VoronDesign/VoronUsers pull request #376
Opened 2021-07-04 17:34 UTC by revnull-src

* [X] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [X] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [X] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [X] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [X] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [X] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [X] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [X] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [X] Submitted STL files are oriented and scaled properly for printing.
  * [X] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Articulating Raspberry Pi 7" Display Mount

#### How was it tested?
Tested by mounting display to frame and testing full range of articulation.

#### Any background context you want to provide?
A giant printer (2.4 350) should have a giant screen. :)

#### Screenshots (if appropriate)
Pictures included in the "Images" subdir.

#### Further notes
None at this time.

2021-07-05 18:27 UTC, KiloQubit requested changes
Thanks for your mod!  Just a minor correction in the README below.

2021-07-05 18:27 UTC, KiloQubit commented on printer_mods/revnull/rpi_7in_display_mount/README.md
> +Assemble the parts in the following orientation making sure not to overtighten/scrip the screws. The movement should be smooth, but tight enough to hold position.
Replace `scrip` with `strip`.

2021-07-06 01:20 UTC, revnull-src commented on printer_mods/revnull/rpi_7in_display_mount/README.md
> +Assemble the parts in the following orientation making sure not to overtighten/scrip the screws. The movement should be smooth, but tight enough to hold position.
Thanks for the typo catch.

2021-07-06 12:05 UTC, KiloQubit approved these changes
Thanks for the update!

2021-07-06 12:05 UTC, merged

2021-09-08 17:59 UTC, Fr33man85 commented
Great Display mount, but with one major issue: not usable, if you using the front doors with upper and lower handles :(

is it possible to get the CAD-files?


![20210908_195603_1024x1024_500KB](https://user-images.githubusercontent.com/50385199/132560457-2f05f9aa-233c-418d-9759-bf844d6d73c5.jpg)
![20210908_195610_1024x1024_500KB](https://user-images.githubusercontent.com/50385199/132560465-6b0b62aa-12a6-47f3-ab24-77e8d8c9d136.jpg)
![20210908_195614_1024x1024_500KB](https://user-images.githubusercontent.com/50385199/132560486-bd6eb4cc-e15b-4e69-a3fa-4198922007dc.jpg)
![20210908_195625_1024x1024_500KB](https://user-images.githubusercontent.com/50385199/132560497-299e181e-9ff8-4b23-b2fe-015272347239.jpg)