Initial commit
VoronDesign/VoronUsers pull request #388
Opened 2021-07-19 19:37 UTC by QuackProfit

* [X] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [X] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [X] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [X] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [X] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [X] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [X] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [X] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [X] Submitted STL files are oriented and scaled properly for printing.
  * [X] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
This is a new mod to add mounting support for Adafruit's NeoPixel PCBs on the V0's Y-rail extrusions.

#### How was it tested? 
This mod was tested by myself and another member on the Discord.

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2021-08-03 23:51 UTC, KiloQubit requested changes
Thanks for your mod!

Just a few minor corrections below.

2021-08-03 23:51 UTC, KiloQubit commented on printer_mods/QuackProfit/V0-Adafruit-Y_Rails/README.md
> +* Don't install the printed covers as this stage
Replace `as` with `at`.

2021-08-03 23:51 UTC, KiloQubit commented on printer_mods/QuackProfit/V0-Adafruit-Y_Rails/README.md
> +* Refer to your Controller documentation to find the pin name that controlls the neopixel data signal
Replace `controlls` with `controls`.

2021-08-04 03:09 UTC, QuackProfit commented on printer_mods/QuackProfit/V0-Adafruit-Y_Rails/README.md
> +* Don't install the printed covers as this stage
Fixed.

2021-08-04 03:09 UTC, QuackProfit commented on printer_mods/QuackProfit/V0-Adafruit-Y_Rails/README.md
> +* Refer to your Controller documentation to find the pin name that controlls the neopixel data signal
Fixed.

2021-08-04 03:10 UTC, QuackProfit commented
Thank you for catching my typos! I need to find a good spell checker add-on for VS Code.

2021-08-04 12:21 UTC, KiloQubit approved these changes
Thanks for the update!

2021-08-04 12:21 UTC, merged