Adjustable V0 Bowden Strike Block
VoronDesign/VoronUsers pull request #426
Opened 2021-09-03 21:25 UTC by jgehrig

This is a drop in replacement for the `Endstop_Strike_Block` used with Bowden extruders.

The endstop can be rotated to adjust the X gantry zero point. On my printer, the stock strike block was not large enough to trigger the homing switch before the toolhead crashed. This mod allows the users to more precisely set the zero point.

https://github.com/jgehrig/VoronUsers/tree/jg-endstop/printer_mods/jgehrig/v0_adj_bowden_endstop

2021-09-03 21:28 UTC, jgehrig commented
The `printer_mods` `README.md` modifcation includes a line from #323.

That PR should bemerged first, so we don't get a merge conflict or bad link.

2021-09-11 19:47 UTC, KiloQubit requested changes
Thanks for your mod!  Please see fixes for README below.

2021-09-11 19:47 UTC, KiloQubit commented on printer_mods/README.md
> +| jgehrig | [Adjustable Bowden Endstop](jgehrig/v0_adj_bowden_endstop) | Adjustable Bowden X-Axis endstop strike block | :heavy_check_mark: | :x: | :x: | :x: |
Can you add an `:x:` for the Trident column on both lines?

2021-09-11 19:47 UTC, KiloQubit commented on printer_mods/jgehrig/v0_adj_bowden_endstop/README.md
> +[Fusion 360 Web View](https://a360.co/3fExdho)
this link goes to the view for the V0 display mount for me

2021-10-16 12:54 UTC, KiloQubit commented
@jgehrig are you planning to update the PR to address the review?

2022-08-29 22:48 UTC, cbc02009 commented
Closing due to inactivity.

2022-08-29 22:48 UTC, closed without merging