Dual 5015 blower fan part cooling duct/mount for V0
VoronDesign/VoronUsers pull request #432
Opened 2021-09-06 23:44 UTC by designbydave

* [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
./designbydave/5015_Fan_Ducts_for_V0

#### How was it tested? 
I printed them, installed them and printed several parts with this confirgration

#### Any background context you want to provide?

V0 stock 3010 part cooling fans not enough for printing/cooling PLA, so we add more blow-ie

#### Screenshots (if appropriate)
pics in directory

#### Further notes
first time using github, so, sorry if I'm doing something incorrectly. I probably am. It was suggested by a couple members of the discord server to upload this mod here.

2021-09-18 11:52 UTC, blalor commented
This looks interesting. How's it fare with fast accelerations? Seems like the un-braced mass of the fans could cause them to break the ducts. Would tying them together at the top make sense?

2021-09-18 14:21 UTC, designbydave commented
> 
> 
> This looks interesting. How's it fare with fast accelerations? Seems like the un-braced mass of the fans could cause them to break the ducts. Would tying them together at the top make sense?

I was never able to test it with anything over ~5000 mm/s^2 as the steppers on my V0 would loose steps. Maybe the extra mass of the fans and ducts made that situation worse. So, it seems to drive really high accelerations you will need the more powerful steppers of the V0.1.

I don't think the ducts will break, but there could be some unwanted flexing or motion of the fans. I did consider a spacer to tie the fans together. A simple printed cylinder between the unused mounting holes would be easy to make and install.

2021-09-19 14:38 UTC, KiloQubit requested changes
Thanks for your mod!

Looks like you have some unprintable bridging around the bottom of the fan mount hole
<img width="451" alt="Screen Shot 2021-09-19 at 10 33 29" src="https://user-images.githubusercontent.com/69389593/133931469-20ed7df5-58f5-4228-b35c-d77d35bea139.png">

Is this supposed to be a removable support?  If so, where do you cut it on the right side?  The left side has an obvious gap, but the right side does not.  Also add instructions to the readme to remove it.
<img width="537" alt="Screen Shot 2021-09-19 at 10 35 57" src="https://user-images.githubusercontent.com/69389593/133931562-df3b18ef-0fa8-4b46-b524-dcad2b499d11.png">

2021-09-19 14:38 UTC, KiloQubit commented on printer_mods/README.md
> +| designbydave | [5015 Part Cooling Fan Duct/Mounts for V0](./designbydave/5015_Fan_Ducts_for_V0) | 5015 Part Cooling Fan Duct/Mounts for V0 | :heavy_check_mark: | :x: | :x: | :x: |
Can you add an `:x:` for the Trident column?

2021-09-19 14:38 UTC, KiloQubit commented on printer_mods/designbydave/5015_Fan_Ducts_for_V0/README.md
> +2x M3x20mm BHCS
Can you make this a list, so it doesn't all display on a single line?

```
- 2x M3x20mm BHCS
- 2x M3x50mm BHCS or SHCS
- 4x M3 nuts
```

2021-12-03 04:37 UTC, bdbell commented
I don't see any updates or commits after the request for changes.  Will those changes be coming?

2023-07-17 22:18 UTC, FHeilmann commented
Comments of reviewers were not adressed. Closing as stale, most importantly because at this point this mod is better off being resubmitted than reviving this PR.
If there are any questions, feel free to reach out.

2023-07-17 22:18 UTC, closed without merging