Pi tft43  mount
VoronDesign/VoronUsers pull request #434
Opened 2021-09-08 17:51 UTC by maramauphoto

* [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

#### How was it tested? 

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2021-09-19 17:31 UTC, KiloQubit requested changes
Thanks for your mod!

Please create a directory under your username and move the mod there, e.g. put your mod in `printer_mods/maramao/BTT_piTFT43_mount/` instead of directly in `printer_mods/maramao/` where it is now.

You have two STLs there that seem identical except chamfers on the underside of the holes - `piTFT43_mount.stl` (good) and `BTT_piTFT43_mount.stl` (missing chamfer on hole underside) - did you mean to only include `piTFT43_mount.stl`?

2021-09-19 17:31 UTC, KiloQubit commented on printer_mods/README.md
> +|Maramao| [BTT piTFT43 Mount](.\maramao\STL\BTT_piTFT43_mount) | Mount for the BTT piTFT43 screen | :x: | :x: | :heavy_check_mark: | :grey_question: |
This link is broken - the slashes are backwards and the directory is incorrect.  If you move your mod to `printer_mods/maramao/BTT_piTFT43_mount/` as suggested in my other comment, then your link here would be

    [BTT piTFT43 Mount](./maramao/BTT_piTFT43_mount)

Also please add a question mark or an X in the last column (Trident) of the compatibility matrix.

2021-09-19 17:31 UTC, KiloQubit commented on printer_mods/maramao/README.md
> +this is a quick remix based on the work of alanho [BTT_PITFT50_v2_Mount] (https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/alanho/BTT_PITFT50_v2_Mount)
Please remove the space between [] and (), and change the link to relative.  It should be

    [BTT PITFT50 v2 Mount](../../alanho/BTT_PITFT50_v2_Mount)

2021-09-19 17:31 UTC, KiloQubit commented on printer_mods/maramao/README.md
> +this is a quick remix based on the work of alanho [BTT_PITFT50_v2_Mount] (https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/alanho/BTT_PITFT50_v2_Mount)
Capitalize `t` in `This` at the start of the sentence.

2021-09-19 17:31 UTC, KiloQubit commented on printer_mods/maramao/README.md
> +to fit on the screen mount of [sttts's Waveshare 5.5inch mount] (https://github.com/VoronDesign/VoronUsers/blob/master/printer_mods/sttts/Waveshare-5.5-inch-HDMI-AMOLED)
Remove space between [] and () and change link to relative:

    [sttts's Waveshare 5.5inch mount](../../sttts/Waveshare-5.5-inch-HDMI-AMOLED)

2021-09-19 17:31 UTC, KiloQubit commented on printer_mods/maramao/README.md
> +4x M3x6mm
Make this a list so it doesn't show all on one line:

```
- 4x M3x6mm
- 4x M2.5x4mm (included in the BTT PITFT50 v2)
- 500mm ~ 600mm Ribbon Flat Cable for Raspberry Pi Camera (depends on the position of the Raspberry Pi. The included one is too short)
```

2021-09-19 17:31 UTC, KiloQubit commented on printer_mods/maramao/README.md
> +## Instrucions
Replace `Instrucions` with `Instructions`

2021-09-19 17:31 UTC, KiloQubit commented on printer_mods/maramao/README.md
> +Use the mount in [sttts's mods] (https://github.com/VoronDesign/VoronUsers/blob/master/printer_mods/sttts/Waveshare-5.5-inch-HDMI-AMOLED/STLs/Voron-2.4-Mount-Generisch-v6.stl) to mount this to the fr
Remove space between [] and () and change to relative link:

    [sttts's mods](../../sttts/Waveshare-5.5-inch-HDMI-AMOLED/STLs/Voron-2.4-Mount-Generisch-v6.stl)

2021-09-19 17:31 UTC, KiloQubit commented on printer_mods/maramao/README.md
> +
Embed the pictures you have in the README with something like this

```
![Mount side view](Pictures/1.jpg)
![Mount front view](Pictures/2.jpg)
![Display](Pictures/3.jpg)
```

2021-09-20 08:31 UTC, maramauphoto commented
> Thanks for your mod!
> 
> Please create a directory under your username and move the mod there, e.g. put your mod in `printer_mods/maramao/BTT_piTFT43_mount/` instead of directly in `printer_mods/maramao/` where it is now.
> 
> You have two STLs there that seem identical except chamfers on the underside of the holes - `piTFT43_mount.stl` (good) and `BTT_piTFT43_mount.stl` (missing chamfer on hole underside) - did you mean to only include `piTFT43_mount.stl`?

No, I meant to include only the BTT_piTFT43_mount.stl

2021-09-20 21:54 UTC, KiloQubit requested changes
Thanks for the update!

- You still don't have a directory for your mod under the username.  Please create `printer_mods/mramao/BTT_piTFT43_mount/` directory and move your mod files in there
- you have unprintable overhangs on the bottom of two holes, you need to chamfer the holes to avoid that
<img width="371" alt="Screen Shot 2021-09-20 at 17 49 58" src="https://user-images.githubusercontent.com/69389593/134080642-2e35258e-f464-4b83-b209-d6b4551a99bb.png">

- Your STL file is corrupted

2021-09-20 21:54 UTC, KiloQubit commented on printer_mods/maramao/README.md
> +Use the mount in [sttts's mods] (../../sttts/Waveshare-5.5-inch-HDMI-AMOLED/STLs/Voron-2.4-Mount-Generisch-v6.stl) to mount this to the frame.
This still needs space removed between `[]` and `()`

2021-12-03 04:39 UTC, bdbell commented
Will the last two items be updated so the PR can be accepted?

2022-08-29 22:51 UTC, cbc02009 commented
Closing due to inactivity.

2022-08-29 22:51 UTC, closed without merging