Printable 10x11mm chain and magnetic probe for VSW
VoronDesign/VoronUsers pull request #452
Opened 2021-09-21 15:36 UTC by hymness1

* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Quickdraw Probe remix for Voron Switchwire, with macros. There's also a printable and openable 10x11mm chain
#### How was it tested? 
I did, and some others users have tried the Quickdraw Probe.
#### Any background context you want to provide?
No
#### Screenshots (if appropriate)
There are in the folders
#### Further notes
Keep on the good work!

2021-10-02 17:12 UTC, KiloQubit reviewed
Thanks for your mods!  I see that you have a LICENSE file pointing to a different license.  All mods in this repository MUST be GPL3, and there's a license file at the top of the repository to that effect.  We cannot accept any mods here that are not GPL3, so please remove all non-GPL3 content as well as the license file.

2021-10-04 11:53 UTC, hymness1 commented
Hi KiloQubit,

I don't know much about GitHub, but I think I did what you asked me. All
files in my repo that I want merged in VoronUsers are my own and I created
them myself.

If you need anything else please let me know, as I said, I'm a GitNoob ;)
Thanks!

Le sam. 2 oct. 2021, à 13 h 12, KiloQubit ***@***.***> a
écrit :

> ***@***.**** commented on this pull request.
>
> Thanks for your mods! I see that you have a LICENSE file pointing to a
> different license. All mods in this repository MUST be GPL3, and there's a
> license file at the top of the repository to that effect. We cannot accept
> any mods here that are not GPL3, so please remove all non-GPL3 content as
> well as the license file.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/VoronDesign/VoronUsers/pull/452#pullrequestreview-769511607>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQWHJPBR7HWMYPP5LVDB233UE44RFANCNFSM5EOY7MKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-06 01:49 UTC, hymness1 commented
Hi, thanks at least for reaching out :) I'm trying to do things the right
way. I'll reach out at Annex and see if everything would be fine and come
back at you after if that's okay with you.

The chains however are my own, so there shouldn't be any problem. But I
don't know if I'd have to manually do a pull request for that.

Thanks so much for your patience, I suppose I'm not the first noob you
encounter ;)

Le mar. 5 oct. 2021, à 21 h 39, KiloQubit ***@***.***> a
écrit :

> In your README for the Switchwire Quickdraw you say
>
> remixed from the files at Annex Engineering
>
> If you took the CAD or STL file from Annex and then modified it, then the
> resulting file is not GPLv3 and cannot be merged into this repository.
> Annex Engineering CAD/STL files are not GPLv3 (they use their own custom
> license), and unless you get written permission from them, you cannot
> distribute your modified version as GPLv3 either. If you do have written
> permission from them, please include it in this PR.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/VoronDesign/VoronUsers/pull/452#issuecomment-935226061>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQWHJPBYCZ2K2QXPDIEBRLTUFOSD7ANCNFSM5EOY7MKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-08 21:37 UTC, KiloQubit commented on printer_mods/README.md
> +|hymness1| [Quickdraw_probe_Voron_Switchwire](./hymness1/Quickdraw_probe_Voron_Switchwire) | Detachable magnetic probe with docking system for VSW | :x: | :x: | :x: | :heavy_check_mark: |
Please add an `:x:` in the Trident column.

Please remove underscores from inside square brackets, that is the text shown to the user:

    [Quickdraw probe Voron Switchwire](./hymness1/Quickdraw_probe_Voron_Switchwire)

Same thing on next line.

2021-10-08 21:53 UTC, KiloQubit commented on printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Klipper_Macros/README.md
> +A tutorial to get all this working will be available [here](https://docs.google.com/document/d/1dSgqjHQ3RNvcPwyRcuyMOceWPvVQUWRSjj3-KcRRMoo/edit?usp=sharing)
This links to an empty document for me.

2021-10-16 18:27 UTC, KiloQubit requested changes
Thanks for your updates!

Looks like there's another unsupported overhang that needs either a chamfer or a built-in support in `chainlink.stl`
<img width="860" alt="Screen Shot 2021-10-16 at 14 06 40" src="https://user-images.githubusercontent.com/69389593/137597761-fb3a71f9-d3e0-4f88-b512-7bd6e5288821.png">

Too steep overhang in `fixed_end.stl`
<img width="578" alt="Screen Shot 2021-10-16 at 14 08 40" src="https://user-images.githubusercontent.com/69389593/137597802-1c1432e8-b89c-4892-8164-49ce5c6d4be5.png">

2021-10-16 18:27 UTC, KiloQubit commented on printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Klipper_Macros/README.md
> +![SW_Y_travel](/printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Pictures/SW_Y_travel.png)
Can you make this a relative reference from this directory?  i.e. it should be

    ![SW_Y_travel](../Pictures/SW_Y_travel.png)

2021-10-16 20:03 UTC, hymness1 commented
Thanks for your feedback. Modifications have been done :)

Le sam. 16 oct. 2021, à 14 h 27, KiloQubit ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
>
> Thanks for your updates!
>
> Looks like there's another unsupported overhang that needs either a
> chamfer or a built-in support in chainlink.stl
> [image: Screen Shot 2021-10-16 at 14 06 40]
> <https://user-images.githubusercontent.com/69389593/137597761-fb3a71f9-d3e0-4f88-b512-7bd6e5288821.png>
>
> Too steep overhang in fixed_end.stl
> [image: Screen Shot 2021-10-16 at 14 08 40]
> <https://user-images.githubusercontent.com/69389593/137597802-1c1432e8-b89c-4892-8164-49ce5c6d4be5.png>
> ------------------------------
>
> In
> printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Klipper_Macros/README.md
> <https://github.com/VoronDesign/VoronUsers/pull/452#discussion_r730296308>
> :
>
> > +
> +The Z endstop microswitch (whether using the modded KeyBak mount or a switch located at Z-max) is only used for initial Z homing if the probe is not already attached to the toolhead. It is a good idea to add `Park_toolhead` to your end_print macro or cancel_print macro, so the probe is virtually always attached to the toolhead.
> +
> +When homing with the probe attached, terminal will report a wrong value for Z position that should be way higher than supposed, in example `probe at 125.000,84.500 is z=236.425000`. It is normal behavior and is a workaround the fact that you can't have 2 different Z endstops. After homing, position of the toolhead is set to probe z_offset.
> +
> +Be sure to add `Dock_probe` in your print_start macro after the bed mesh or other probing actions.
> +
> +Sensorless homing for initial Z homing does work, but I don't recommend it. The KeyBak can be somewhat inconsistent in its tension and can lead to unwanted behavior.
> +
> +If you don't plan to use a Z endstop microswitch or sensorless homing for initial Z homing, don't change your `endstop_pin` in the `stepper_z` section of `printer.cfg`.
> +
> +# About the modded KeyBak mount and the endstop microswitch located at Z_min (or sensorless homing at Z_min) and Y travel
> +
> +The Switchwire has about 230mm of print area in the Y direction, but has around 250mm of Y travel (mine has 257mm), from the endstop to the endblock. About 20 of those millimeters are located outside the bed at the front when the bed is pushed all the way to the rear of the printer. At this location, the nozzle and the part cooling ducts can be clear of the bed when homing at Z_min. The default `printer.cfg` for the VSW with an SKR Mini E3 V2 calls for 0 as position_min and 250 as position_max, whilst it should be, at least that is my case, -25 as position_min and 232 as position_max. When populating the variables in `dock_macros.cfg`, be sure to enter an existing value for `variable_y_min`, and that this value is located outside the bed. If you are using default config for `printer.cfg`, 0 should be a safe coordinate. If you changed the config file for the real travel in the Y axis, -20 should be a safe coordinate. Failure to enter an existing or safe value could at best prevent you from homing with the message `Move out of range`, or at worst crash the nozzle into the bed.
> +
> +![SW_Y_travel](/printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Pictures/SW_Y_travel.png)
>
> Can you make this a relative reference from this directory? i.e. it should
> be
>
> ![SW_Y_travel](../Pictures/SW_Y_travel.png)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/VoronDesign/VoronUsers/pull/452#pullrequestreview-781380110>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQWHJPCVWW32D54M23ZT3KDUHG7YVANCNFSM5EOY7MKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-16 20:23 UTC, KiloQubit commented on printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Klipper_Macros/README.md
> +![SW_Y_travel](/printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Pictures/SW_Y_travel.png)
Thanks.  Can you also update this README image link?

2021-10-16 20:50 UTC, hymness1 commented
Done

Le sam. 16 oct. 2021, à 16 h 23, KiloQubit ***@***.***> a
écrit :

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Klipper_Macros/README.md
> <https://github.com/VoronDesign/VoronUsers/pull/452#discussion_r730309504>
> :
>
> > +
> +The Z endstop microswitch (whether using the modded KeyBak mount or a switch located at Z-max) is only used for initial Z homing if the probe is not already attached to the toolhead. It is a good idea to add `Park_toolhead` to your end_print macro or cancel_print macro, so the probe is virtually always attached to the toolhead.
> +
> +When homing with the probe attached, terminal will report a wrong value for Z position that should be way higher than supposed, in example `probe at 125.000,84.500 is z=236.425000`. It is normal behavior and is a workaround the fact that you can't have 2 different Z endstops. After homing, position of the toolhead is set to probe z_offset.
> +
> +Be sure to add `Dock_probe` in your print_start macro after the bed mesh or other probing actions.
> +
> +Sensorless homing for initial Z homing does work, but I don't recommend it. The KeyBak can be somewhat inconsistent in its tension and can lead to unwanted behavior.
> +
> +If you don't plan to use a Z endstop microswitch or sensorless homing for initial Z homing, don't change your `endstop_pin` in the `stepper_z` section of `printer.cfg`.
> +
> +# About the modded KeyBak mount and the endstop microswitch located at Z_min (or sensorless homing at Z_min) and Y travel
> +
> +The Switchwire has about 230mm of print area in the Y direction, but has around 250mm of Y travel (mine has 257mm), from the endstop to the endblock. About 20 of those millimeters are located outside the bed at the front when the bed is pushed all the way to the rear of the printer. At this location, the nozzle and the part cooling ducts can be clear of the bed when homing at Z_min. The default `printer.cfg` for the VSW with an SKR Mini E3 V2 calls for 0 as position_min and 250 as position_max, whilst it should be, at least that is my case, -25 as position_min and 232 as position_max. When populating the variables in `dock_macros.cfg`, be sure to enter an existing value for `variable_y_min`, and that this value is located outside the bed. If you are using default config for `printer.cfg`, 0 should be a safe coordinate. If you changed the config file for the real travel in the Y axis, -20 should be a safe coordinate. Failure to enter an existing or safe value could at best prevent you from homing with the message `Move out of range`, or at worst crash the nozzle into the bed.
> +
> +![SW_Y_travel](/printer_mods/hymness1/Quickdraw_probe_Voron_Switchwire/Pictures/SW_Y_travel.png)
>
> Thanks. Can you also update this README image link?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/VoronDesign/VoronUsers/pull/452#discussion_r730309504>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQWHJPC66L5EPBA32BARHPDUHHNNDANCNFSM5EOY7MKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-16 21:17 UTC, KiloQubit approved these changes
Thanks for the updates!

2021-10-16 21:17 UTC, merged