adds larger spool holder Voron Zero
VoronDesign/VoronUsers pull request #504
Opened 2021-10-20 19:55 UTC by kleinejan

* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Larger spool holder V0
It is actually a modified voron part, but now can receive bigger spools

#### How was it tested? 
It's printed and working

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2021-12-07 22:06 UTC, cbc02009 requested changes

2021-12-07 22:06 UTC, cbc02009 commented on printer_mods/README.md
> +| Kleinejan | [V0 Large spool holder](./kleinejan/V0-large-spool-holder) | Voron0 Large spool holder | :heavy_check_mark: | :x: | :x: | :x: | :x: |
Please make sure this is added in alphabetical order

2022-07-22 11:08 UTC, newphreak commented
@kleinejan can you make the requested changes?

2022-08-29 22:45 UTC, cbc02009 commented
Closing due to inactivity.

2022-08-29 22:45 UTC, closed without merging