Voron0_Block_and_Tackle_Z_Belt
VoronDesign/VoronUsers pull request #509
Opened 2021-10-23 09:22 UTC by Fleafa

* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
This is a  block & tackle Z belt implementation for the Voron 0 / Voron 0.1 using the original V0 NEMA14 motor with 40T & 16T pulleys, combining with the 2:1 of the block and tackle, giving a 5:1 ratio (can be increased to 8:1). Combinged with the friction added by the B&T belt path, this means there is no Z drop on power loss. All screws are V0.1 BoM. Compatible with both V0 and V0.1 bed positions through a single printed part swap.

#### How was it tested? 
Installed on my V0 for several weeks, printing daily. Serial V0.880 assigned with this mod installed.

#### Any background context you want to provide?
I had gathered V0 parts, bvut had been unable to begin the build until after the V0.1 update. I really wanted to avoid the possibility of Z artefacts but didn't want to waste the motors I had. The existing belted Z mod is nice, but I wanted a NEMA14 solution requiring no disassembly or panel cuts which would also avoid Z drop on power loss.

#### Screenshots (if appropriate)
![image](./Images/Block_and_Tackle_Z_Belt_Render.png)
![image](./Images/Block_and_Tackle_Z_Belt_Drawing.png)

#### Further notes

2021-12-09 15:00 UTC, cbc02009 requested changes
Please remove all spaces from file and folder names.

2021-12-10 13:37 UTC, Fleafa commented
> 

Apologies, I forgot to remove those files when I uploaded the renamed ones.

2021-12-10 13:38 UTC, Fleafa commented
> Please remove all spaces from file and folder names.
Apologies, I forgot to remove those files when I uploaded the renamed ones.

2021-12-12 17:37 UTC, cbc02009 approved these changes

2021-12-15 23:00 UTC, merged