1515ledmod
VoronDesign/VoronUsers pull request #518
Opened 2021-11-06 09:25 UTC by newphreak

* [x ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ x] Submitted STL files are oriented and scaled properly for printing.
  * [ x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
A snap in led mount for the v0
#### How was it tested? 
Mounted and in use
#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2021-12-07 00:10 UTC, cbc02009 approved these changes

2021-12-07 00:11 UTC, cbc02009 submitted a review, later dismissed
Can you rebase this to fix the conflicts? Otherwise it looks fine.

2021-12-07 01:31 UTC, KiloQubit requested changes

2021-12-07 01:31 UTC, KiloQubit commented on printer_mods/README.md
> +| | [adxl345 skirt keystone](./Jon/adxl345_skirt_keystone) | Skirt keystone for ADXL345 using Microfit 3.0 | :x: | :x: | :heavy_check_mark: | :grey_question: | :grey_question: | :heavy_check_mark: |
there's too many columns, that last heavy check mark has no corresponding column, please remove it

2021-12-07 22:12 UTC, cbc02009 commented
Looks like there are some merge conflicts that need to be resolved still to finish the review.

2021-12-08 00:29 UTC, KiloQubit approved these changes

2021-12-08 00:30 UTC, merged