Tridentified V2.4 Power Inlet - Side mounted power inlet like Trident
VoronDesign/VoronUsers pull request #528
Opened 2021-11-17 08:06 UTC by Amarpal89

* [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Tridentified V2.4 Skirts : A mod to backport the more convenient side mounting for the power inlet to the V2.4. These skirts are based on edwardyeeks "z-drive tensioner mod" compatible skirts and have power inlet and switch holes of equal geometry to the standard voron parts. 

#### How was it tested? 
The filtered inlet versions have been printed and installed by a few voron community members. Not all versions have been printed and tested but as they are based on existing voronusers repo parts with fairly straightforward modification to permit power inlet mounting I cannot foresee any issues with print-ability/fitment.

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

As these skirts have the prerequisite of requiring the user to have edwardyeeks z-drive tensioner mod, he and I agreed that it would be best to have them located within edwardyeeks folder.

2021-12-05 05:45 UTC, edwardyeeks reviewed
Overall, this looks good 👍 I would sign off with your name @Amarpal89 in the readme just so that everyone is aware that this derivative of the mod is done by you.

2021-12-05 05:45 UTC, edwardyeeks approved these changes

2021-12-06 23:49 UTC, cbc02009 requested changes
Since you made these changes and not edwardyeeks this should be filed under your username and not theirs.

2021-12-06 23:55 UTC, Amarpal89 commented
> Since you made these changes and not edwardyeeks this should be filed under your username and not theirs.

By that do you mean just adding a new row with my username in the root README.md -or- also to put them in a folder under my username?

2021-12-07 01:23 UTC, KiloQubit commented
The changes are fine in the directory they're in, because the original author has approved it.  Did you put your own name in the readme as @edwardyeeks has asked?

2021-12-07 01:24 UTC, cbc02009 commented
> > Since you made these changes and not edwardyeeks this should be filed under your username and not theirs.
> 
> By that do you mean just adding a new row with my username in the root README.md -or- also to put them in a folder under my username?

Sorry, I missed the comment by @edwardyeeks approving adding it to their folder. My mistake.

2021-12-07 01:26 UTC, cbc02009 requested changes

2021-12-07 01:26 UTC, cbc02009 commented on printer_mods/README.md
> +| |[Tridentified V2.4 Power Inlet](edwardyeeks/Tridentified_V2.4_Power_Inlet) |Trident style side power inlet for V2.4 using Z Drive Motor Tensioner Mod |:x: |:x: |:heavy_check_mark: |:x:|
Please add the appropriate mark to the trident column

2021-12-07 06:00 UTC, Amarpal89 commented
Have added myself to the readme table as requested by @edwardyeeks and added correct mark to trident column.

2021-12-07 21:46 UTC, cbc02009 commented
> Have added myself to the readme table as requested by @edwardyeeks and added correct mark to trident column.

Sorry for the confusion, you don't need to add your own section to the readme since the mod is going into someone else's folder. Can you undo commit 12557b3 ?

2021-12-07 23:13 UTC, Amarpal89 commented
> > Have added myself to the readme table as requested by @edwardyeeks and added correct mark to trident column.
> 
> Sorry for the confusion, you don't need to add your own section to the readme since the mod is going into someone else's folder. Can you undo commit [12557b3](https://github.com/VoronDesign/VoronUsers/commit/12557b3293c88cf6656ec29924d32b829200b3d0) ?

I've reverted the last commit (and merged upstream changes). Should be all good now.

2021-12-08 00:43 UTC, KiloQubit approved these changes

2021-12-08 00:44 UTC, merged