C525 Webcam Holder
VoronDesign/VoronUsers pull request #624
Opened 2022-02-14 14:40 UTC by LeoDova

* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
A C525 webcam holder

#### How was it tested? 
Printed and shown in pictures

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2022-04-04 23:03 UTC, cbc02009 requested changes

2022-04-04 23:03 UTC, cbc02009 commented on printer_mods/willikonk/webcam_holder/README.md
> +This is a webcam holder to attach the [Logitech C525](https://www.amazon.com/Logitech-Webcam-Portable-Calling-Autofocus/dp/B004WO8HQ4/ref=sr_1_3?crid=343YW4HG90NPC&keywords=c525&qid=1644847788&sprefi
remove ref and everything after it in the amazon link. it's tracking metadata.

2022-07-22 10:49 UTC, newphreak commented
@LeoDova can you make the requested changes? :)

2022-07-22 23:53 UTC, MapleLeafMakers commented
CAD Files need to be provided in STEP or SCAD format. you can include the .ipt file *in addition* to one of these.

2022-07-24 00:33 UTC, newphreak commented
![image](https://user-images.githubusercontent.com/640287/180627323-e29df671-801d-48e3-bbc9-9a8d00cb7329.png)
this should be chamfered so it doesn't need supports.

2022-07-24 01:13 UTC, newphreak approved these changes
Looks good to me

2022-07-24 12:33 UTC, cbc02009 approved these changes

2022-07-24 12:34 UTC, cbc02009 commented
@LeoDova this is good to go, but there are merge conflicts in the main readme.md file that need to be sorted out.

2022-07-24 13:09 UTC, newphreak commented
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
![image](https://user-images.githubusercontent.com/640287/180648452-a8e613bf-1a1a-47c5-b2a3-267b332d5e8e.png)

2023-12-23 00:49 UTC, FHeilmann commented
Hi, 

I want to thank you for your submission and want to personally apologize that your submission has not gotten the review it deserves.
We are in the process to restructure the repo to streamline reviews and hopefully solve this issue in the future.

Unfortunately, this means that we will require you to resubmit the mod under the new system.

Please check [here](https://github.com/VoronDesign/VoronUsers/wiki/VoronUsers-Overhaul) for details and instructions on how to proceed. 
If you have any questions, please reach out in the #voronuser_mods channel on the VoronDesign discord.
If you have since moved on from this mod and don't want to resubmit, no further action is necessary from your side.

Bests,

Florian a.k.a. Haribro

2023-12-23 00:49 UTC, closed without merging