Clip on door frame
VoronDesign/VoronUsers pull request #628
Opened 2022-02-16 03:20 UTC by scanlory

* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
This mod adds a frame around the front door panels to stiffen and seal the doors when using modified hinges.

#### How was it tested? 
The modification was printed and tested on my V2.4.

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2022-04-04 22:51 UTC, cbc02009 requested changes

2022-04-04 22:51 UTC, cbc02009 commented on printer_mods/scanlory/clip_on_door_frame/README.md
> + This design builds on [Alexander-T-Moss](https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/AlexanderT-Moss/270-Clamping-Hinges) 270 degree hinges by adding a clip-on frame around th
please use a relative link here.

2022-04-04 22:51 UTC, cbc02009 commented on printer_mods/scanlory/clip_on_door_frame/README.md
> + ![full_front_view.jpg](https://github.com/scanlory/VoronUsers/blob/clip_on_door_frame/printer_mods/scanlory/clip_on_door_frame/Images/full_front_view.jpg)
please change to relative links.

2022-04-09 21:18 UTC, scanlory commented on printer_mods/scanlory/clip_on_door_frame/README.md
> + ![full_front_view.jpg](https://github.com/scanlory/VoronUsers/blob/clip_on_door_frame/printer_mods/scanlory/clip_on_door_frame/Images/full_front_view.jpg)
Updated to relative links.

2022-04-10 10:27 UTC, cbc02009 approved these changes

2022-04-10 10:29 UTC, cbc02009 requested changes

2022-04-10 10:29 UTC, cbc02009 commented on printer_mods/scanlory/clip_on_door_frame/README.md
> + This design builds on [Alexander-T-Moss](../AlexanderT-Moss/270-Clamping-Hinges) 270 degree hinges by adding a clip-on frame around the front doors to provide better sealing and stiffining of the fr
Needs one more ../ for the link to work.

2022-04-16 23:44 UTC, cbc02009 approved these changes

2022-04-23 14:23 UTC, merged