Add Trident Parts Design Logo and correct Typos in README files
VoronDesign/VoronUsers pull request #646
Opened 2022-02-27 16:47 UTC by GadgetAngel

* [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

/printer_mods

#### How was it tested? 

A Voron User on discord requested someone design the Trident Parts Design Logo, so I created this Cricut Logo file and then they requested the .stl files so they can print out the logo in plastic. I then created the .stl files in Fusion 360.  They printed it out and I did not hear back from them complaining of any issues so I assume everything is working correctly.

I also updated the README files to describe the contents of each directory and added a URL link for the directory paths so the user can just click and be taken to the appropriate directory.

#### Any background context you want to provide?

This add the Trident Parts Design Logo to the rest of my Logo collection.

#### Screenshots (if appropriate)

![Trident_DLogo](https://user-images.githubusercontent.com/33468777/155891382-e56e50fe-ce0a-40e0-9529-ad18b182ea8b.png)
![Trident_DLogo_250_Rear_Panel stl](https://user-images.githubusercontent.com/33468777/155891383-14149275-226d-4002-9037-d4cd31d1e2b5.png)
![Trident_DLogo_CAD stl](https://user-images.githubusercontent.com/33468777/155891384-72d09859-03c1-49d2-8ab2-5b9a4edbbb48.png)
![Trident_DLogo_WOHexOutline2jpg](https://user-images.githubusercontent.com/33468777/155891385-1c5082bf-02e6-46ac-bf2d-3601d66f3bf9.jpg)

#### Further notes

2022-03-16 19:08 UTC, cbc02009 requested changes
Can you remove the .vscode folder?

2022-03-23 20:03 UTC, GadgetAngel commented
> Can you remove the .vscode folder?

I will try to remove it now

2022-03-23 20:13 UTC, GadgetAngel commented
> Can you remove the .vscode folder?

Removed

2022-03-31 22:43 UTC, cbc02009 requested changes

2022-04-04 19:56 UTC, GadgetAngel commented on .vscode/ltex.dictionary.en-US.txt
> +Voron
Ok let us try this again. I think I deleted it. So it should be removed now

2022-04-04 20:00 UTC, GadgetAngel commented on .vscode/ltex.dictionary.en-US.txt
> +Voron
removed, I hope

2022-04-04 22:07 UTC, cbc02009 approved these changes

2022-04-04 22:07 UTC, merged