Pull-out_electrical_store for Voron 2.4
VoronDesign/VoronUsers pull request #690
Opened 2022-04-16 17:29 UTC by zzp8202

* [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submission includes a CAD file in the form of a `.STEP` or `.SCAD` file
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

#### How was it tested? 

#### Any background context you want to provide?

#### Screenshots (if appropriate)

#### Further notes

2022-04-18 20:49 UTC, cbc02009 requested changes

2022-04-18 20:49 UTC, cbc02009 commented on printer_mods/ZZP8202/Pull-out_electrical_store/README.md
> +| Creator | Mod title | Description | V0 | V1.8 | V2.4 | VSW | Trident |
this doesn't need to go in your readme file. it's only for the main one in the printer_mods directory.

2022-04-18 20:49 UTC, cbc02009 commented on printer_mods/ZZP8202/Pull-out_electrical_store/README.md
> +Only aimed at Voron V2.4 350mm printer now.
Can you put this in bold so users can't miss it?

2022-04-18 20:49 UTC, cbc02009 commented on printer_mods/ZZP8202/Pull-out_electrical_store/README.md
> +待补充 to be supplemented
We need a full BOM for the project.

2022-04-18 20:49 UTC, cbc02009 commented on printer_mods/ZZP8202/Pull-out_electrical_store/README.md
> +https://www.youtube.com/embed/9XUpTigEtQ4
Written instructions are also very helpful for users.

2022-04-21 21:41 UTC, cbc02009 requested changes

2022-04-21 21:41 UTC, cbc02009 commented on printer_mods/ZZP8202/Pull-out_electrical_store/README.md
> +>|Cables|[Cable Chain](https://www.amazon.com/Befenybay-Internal-Flexible-Machines-10mmX20mm/dp/B07SFFT1K5/ref=sr_1_3?crid=39NLBNYTC6OZX&keywords=Cable%2BChain&qid=1650390801&sprefix=cable%2Bchain%2C
everything except `https://www.amazon.com/Befenybay-Internal-Flexible-Machines-10mmX20mm/dp/B07SFFT1K5` can be deleted from this link. it's just tracking data.

2022-04-21 21:41 UTC, cbc02009 commented on printer_mods/ZZP8202/Pull-out_electrical_store/README.md
> +>|Motion|[450mm Guide_rail](https://www.amazon.com/dp/B08C9PK2L8/ref=syn_sd_onsite_desktop_390?pd_rd_plhdr=t&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzSVlYOU5IVk4xRENCJmVuY3J5cHRlZElkPUEwMjQzNTA3MlNCNkFTRUlVV
same with this link delete /ref and everything after.

2022-04-23 14:33 UTC, cbc02009 commented
One last question, do you know if this will fit with the v2.4r2 z assemblies? If it won't or you're not sure you might want to add a note saying that it's only for v2.4r1.

2022-04-23 17:54 UTC, zzp8202 commented
> One last question, do you know if this will fit with the v2.4r2 z assemblies? If it won't or you're not sure you might want to add a note saying that it's only for v2.4r1.

Based on observations, it is compatible with V2.4 R2 except the side panels (option), anyway, I added the note in the readme.

BTW: Thank you for your hard work. Voron is a great project.

2022-04-25 11:47 UTC, cbc02009 commented
Sorry, just noticed there's a space in the [STEEL CORNER_LBSB6-2020_X8.pdf](https://github.com/VoronDesign/VoronUsers/pull/690/files#diff-be7a8f8e37cb0fb26622aa862bc4497467455be451238676aa295789b10c4c61) filename. please remove it (and make sure there aren't any more that I missed...) then we should be all set.

2022-04-25 17:34 UTC, zzp8202 commented
> Sorry, just noticed there's a space in the [STEEL CORNER_LBSB6-2020_X8.pdf](https://github.com/VoronDesign/VoronUsers/pull/690/files#diff-be7a8f8e37cb0fb26622aa862bc4497467455be451238676aa295789b10c4c61) filename. please remove it (and make sure there aren't any more that I missed...) then we should be all set.

It's done.

2022-04-26 17:13 UTC, cbc02009 approved these changes

2022-04-26 17:13 UTC, merged